# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oneplus/oneplus3/setup-makefiles.sh

PRODUCT_PACKAGES += \
    libloc_api_v02 \
    libtime_genoff \
    datastatusnotification \
    embms \
    fastdormancy \
    QtiTelephonyService \
    shutdownlistener \
    TimeService \
    CNEService \
    com.qualcomm.location \
    dpmserviceapp \
    qcrilmsgtunnel \
    QtiTetherService \
    colorservice \
    qcnvitems \
    qcrilhook

$(call inherit-product, vendor/qcom/binaries/msm8996/graphics/graphics-vendor.mk)

$(call inherit-product, vendor/zuk/z2/vendor/copyfiles.mk)
