# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/zuk/msm8996-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter z2_plus z2_row,$(TARGET_DEVICE)),)

endif
